### ISSUE TITLE
Null Pointer Dereference errors in ESP8266_Wifi_Deauther.fap in extra apps pack

### ISSUE THREAD

**Issue by jlaughter** [DarkFlippers/unleashed-firmware#108]
### Describe the bug.

Null Pointer Dereference errors in ESP8266_Wifi_Deauther.fap in extra apps pack when any menu item is selected, with or without an ESP8266 connected

### Reproduction

Launch app ESP8266_Wifi_Deauther.fap
Select any menu item
Enjoy crash

**Comment by xMasterX** [comment]
This is why this apps is not included with firmware and not present in this repo, they are not stable
And since we don’t have that app here, i recommend contacting author
https://github.com/Timmotools/flipperzero_esp8266_deautherv2

Apps in extra pack are just built from sources, with minimal changes(like some code was unable to compile at all)
