### ISSUE TITLE
KeeLoq bug : switch manufacturer

### ISSUE THREAD

**Issue by neoteknic** [DarkFlippers/unleashed-firmware#214]
### Describe the bug.

With my subghz file evrything work file until sometime the manufacturer change (to a random one), so the remote become unusable.
Original manufacturer : ecostar (copied from a remote + sync with the garage door).
Change randomly at subghz file open.
This bug happen since 2 or 3 firmware.

### Reproduction

1. Use the ecostar file, still show Ecostar manufacturer
2. Close subghz
3. Open the subghz file
4. Wrong manufacturer (random bug)

### Target

unlshd-020

**Comment by xMasterX** [comment]
it was fixed couple releases ago, your file was made on old firmware, so it doesn’t have manufacturer in it
and every time you open it, it runs through all manufacturers, due to algorithm it can detect some false positives 

capture and save that signal again using latest release
don't use old capture if this issue is critical to you
