### ISSUE TITLE
Extern C1101 dosent work anymore

### ISSUE THREAD

**Issue by oldbug62** [DarkFlippers/unleashed-firmware#457]
### Describe the bug.

My external C1101 modul dosent work anymore flipper freze when i turn to external. anybody have the same issue?

unlshd-047

### Reproduction

put c1101 at gpio
switch sub-ghz
flipper freze

other moduls work (nrf24)

**Comment by awnyel** [comment]
I noticed same issue it only catches few buttons from few of the remotes

**Comment by krolchonok** [comment]
What module do you have? DIY? Or a purchased fee?

**Comment by xMasterX** [comment]
We tested external radio many times, and your issue is not related to firmware at all

Issue comes from bad contact or broken module
If you made it yourself, check your connections, and clean up flux after soldering, this causes issues too

Latest firmware can't freeze in subghz read, if module is working properly and connected properly, so check your module and its connections, try different one

**Comment by awnyel** [comment]
it's
 just impossible since all was working perfectly and I tested on a few boards and cc modules also different keyfobs with the same results.

**Comment by krolchonok** [comment]
> it's
>  just impossible since all was working perfectly and I tested on a few boards and cc modules also different keyfobs with the same results. 

on which version does everything work for you?

**Comment by awnyel** [comment]
i just updated yesterday now i tried to downgrade to get them back without luck. and this problem is across all fw with latest updates.

**Comment by awnyel** [comment]
and it worked like a month ago

**Comment by oldbug62** [comment]
@awnyel  exactly the same here
