### ISSUE TITLE
SubGhz chat in CLI cannot output RF signal on external CC1101 module anymore.

### ISSUE THREAD

**Issue by BrunoKlu** [DarkFlippers/unleashed-firmware#458]
When using subghz chat commands, flipper now only outputs radio signal on internal module but refuses to output on external one

**Comment by hotdjdave** [comment]
I am having a similar issue.  When using F0 to open a gate using Sub-GHz CAME_brute_force it now only works via the internal antenna. Using the external antenna with my attached CC1101 module used to work fine, but now does not. I'm not certain, but the issue seems to correspond with the update.

Also, the "TEST" option under the Sub-GHz menu is now missing.  

These issues seem to coincide with the update.

**Comment by BrunoKlu** [comment]
Here internal and external are working fine within Flipper, the only issue is when using CLI chat for me

**Comment by xMasterX** [comment]
Fixed in dev branch and will be in next release
