### ISSUE TITLE
NFC Magic Gen4 GTU Password Inverted

### ISSUE THREAD

**Issue by liszkai** [DarkFlippers/unleashed-firmware#579]
### Describe the bug.

NFC Magic app use GTU password inverted as Proxmark3.

### Reproduction

Create password for magic gtu like  "01 02 03 04"
use pm3 to read card with password "04 03 02 01"
and vice versa...

![PM3PWD](https://github.com/DarkFlippers/unleashed-firmware/assets/57450989/271374b4-4199-4d44-b3c9-8bb3916c8b63)
![F0_pwd1](https://github.com/DarkFlippers/unleashed-firmware/assets/57450989/3e93e60e-8049-4101-a207-a9efb8ce0904)
![F0_pwd2](https://github.com/DarkFlippers/unleashed-firmware/assets/57450989/be03273a-2753-415f-bebe-a65a2af7e94c)
![F0_pwd3](https://github.com/DarkFlippers/unleashed-firmware/assets/57450989/e2492734-e7ab-4724-8252-5dee20ec2e91)
![F0_pwd4](https://github.com/DarkFlippers/unleashed-firmware/assets/57450989/50785246-d14c-449e-81f9-d42419a05055)

**Comment by Leptopt1los** [comment]
@liszkai This behavior is due to the different byte ordering in this scene and in proksmark3 cli. Unfortunately, we cannot change the byte order in NFC Magic, as this will be an unexpected change for users who do not use Proxmark and are accustomed to this form of password

You can read more about byte order at these links:
https://en.wikipedia.org/wiki/Bit_numbering
https://en.wikipedia.org/wiki/Endianness
