### ISSUE TITLE
Marauder deauth stopped working since Ver. 66 

### ISSUE THREAD

**Issue by defconeinzz** [DarkFlippers/unleashed-firmware#669]
### Describe the bug.

Hey, for some reason the deauth attack with a marauder flashed wifi board stopped working since the last FW update (66) - downgraded to V.65, works fine again 

### Reproduction

1. Installed FW V.65 - deauth on TV works like a charm
2. Upgraded FW to V.66  - deauth not working (worked only once with massive beacon attack added)
3. Downgrade to FW v65 - works again (every time) 

### Target

Samsung Smart TV

**Comment by xMasterX** [comment]
How marauder fw is related to this repo?
Flipper and companion app is used only for control of esp32 via uart, we are using original marauder companion app with minimal modifications(saving power state and some keyboard changes), if you believe that issue is in the flipper's app, create issue in original repo

I don't see any connection between unleashed firmware versions and deauth not working on your tv which is works via esp32, and flipper acts only as keyboard to send commands
