### ISSUE TITLE
Sub GHZ Remote App empty

### ISSUE THREAD

**Issue by AztecCodes** [DarkFlippers/unleashed-firmware#763]
Solved.

**Comment by xMasterX** [comment]
What do you mean by "original" app?

and all what you described is not an issue, its empty because you have no map files in the folder, by clicking back it opens menu where you can make those map files or edit them
create map file, configure it, and app will not launch on `<Empty>` folder, because folder now will have your map files in it

**Comment by AztecCodes** [comment]
@xMasterX With the original App I mean the app you can install from the official App Store.

**Comment by xMasterX** [comment]
> @xMasterX With the original App I mean the app you can install from the official App Store.

this is same app actually

**Comment by AztecCodes** [comment]
@xMasterX The official app just notices the 3rd party firmware and behaves like this because of that.
